{
  task_topic: "move_base_simple/goal",
#  grid_topic: "/grid_inflated",
  grid_topic: "occupancy/accumulated",
  path_topic: "trajectory",
  path_topic_vis: "path_visualization",
  search_type: "theta",
#  global_frame: "local_map_lidar",
#  base_frame: "base_link",
  global_frame: "local_map",
  base_frame: "isns_link"
}
#Available planners:  	  "bfs" - BFS
#                         "dijkstra" - Dijkstra
#                         "astar" - A*
#                         "jp_search" - JP (JumpPoint)
#                         "theta" - Theta*
