{
  task_topic: "move_base_simple/goal",
  grid_topic: "/grid_inflated",
  path_topic: "trajectory",
  path_topic_vis: "path_visualization",
  search_type: "theta",
  global_frame: "local_map_lidar",
  base_frame: "base_link"
}
#Available planners are:  "bfs" - BFS
#                         "dijkstra" - Dijkstra
#                         "astar" - A*
#                         "jp_search" - JP (JumpPoint)
#                         "theta" - Theta*
