{
  odom_topic: "odometry",
  task_topic: "move_base_simple/goal",
  grid_topic: "occupancy/accumulated",
  path_topic: "planning_node/trajectory",
  path_topic_vis: "path_visualization",
  search_type: "astar"
}